/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelaInicial;

import Classe.Categoria;
import Classe.Conta;
import Classe.Fornecedor;
import Classe.ListaConta;
import Classe.Tipo_Conta;
import Dao.CategoriaDao;
import Dao.ContaDao;
import Dao.FornecedorDao;
import Dao.Tipo_ContaDao;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author fmoliveira
 */
public class EditarConta extends javax.swing.JFrame {
private int id_item=0;
    /**
     * Creates new form EditarCOnta
     */
    public EditarConta() {
        initComponents();
    }
   public EditarConta(int id) {
       int id_item= id;
        initComponents();
        this.setLocationRelativeTo(null);
         this.getContentPane().setBackground(Color.white);
           ContaDao dao = new ContaDao();
       
       
               Tipo_Conta tipo = new Tipo_Conta();
        Tipo_ContaDao lista_tipo = new Tipo_ContaDao();
        
        Categoria categoria = new Categoria();
        CategoriaDao lista_categoria = new CategoriaDao();
        
        Fornecedor fornecedor = new Fornecedor();
        FornecedorDao lista_fornecedor = new FornecedorDao();
        
        
        ArrayList tipos = lista_tipo.RetornarTipos(tipo);
       
        ArrayList categorias = lista_categoria.RetornarCategorias(categoria);
        ArrayList fornecedores = lista_fornecedor.RetornarFornecedores(fornecedor);

        
        
        this.C_tipos.removeAllItems();
        this.C_categorias.removeAllItems();
        this.C_fornecedores.removeAllItems();
        this.txt_id_conta.setText(String.valueOf(id_item));
        //tipos
        for (int i = 0; i< tipos.size();i++){
           String str = tipos.get(i).toString();
           
            this.C_tipos.addItem(tipos.get(i));
            System.out.print(str);
        }
        
        //fornecedores
        for (int i = 0; i< fornecedores.size();i++){
           String str = fornecedores.get(i).toString();
          
            this.C_fornecedores.addItem(fornecedores.get(i));
            System.out.print(str);
        }
        
        //categorias
        for (int i = 0; i< categorias.size();i++){
           String str = categorias.get(i).toString();
           
            this.C_categorias.addItem(categorias.get(i));
            System.out.print("categoria"+str);
        }
        
        ListaConta conta = new ListaConta();
        
        conta = dao.CarregaEditaConta(id);
        
        System.out.println("id_conta: "+id);
        System.out.println("titulo: "+conta.getTitulo_conta());
         System.out.println("data venc: "+conta.getData_vencimento_inicio());
          System.out.println("n documento: "+conta.getNumero_documento());
           System.out.println("categoria: "+conta.getNome_categoria());
            System.out.println("fornecedor: "+conta.getNome_fornecedor());
             System.out.println("status: "+conta.getStatus());
              System.out.println("nome_tipo: "+conta.getNome_tipo());
               System.out.println("valor conta: "+String.valueOf(conta.getValor_conta()));
               System.out.println("descricao: "+conta.getDescricao());
               System.out.println("valor conta: "+String.valueOf(conta.getValor_conta()));
               System.out.println("valor conta: "+String.valueOf(conta.getQtd_parcelas()));
        
        this.input_titulo.setText(conta.getTitulo_conta());
        this.input_data_vencimento.setText(conta.getData_vencimento_inicio());
        this.input_numero_documento.setText(conta.getNumero_documento());
        this.C_categorias.setSelectedItem(conta.getNome_categoria());
        this.C_fornecedores.setSelectedItem(conta.getNome_fornecedor());
        this.C_status.setSelectedItem(conta.getStatus());
        this.C_tipos.setSelectedItem(conta.getNome_tipo());
        this.input_valor.setText(String.valueOf(conta.getValor_conta()));
        this.txt_descricao.setText(conta.getDescricao());
        this.input_valor.setText(String.valueOf(conta.getValor_conta()));
        this.C_parcela.setSelectedItem(String.valueOf(conta.getQtd_parcelas()));
      

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnRegistrar1 = new javax.swing.JButton();
        input_titulo = new javax.swing.JTextField();
        input_data_vencimento = new javax.swing.JFormattedTextField();
        C_parcela = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        C_status = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_descricao = new javax.swing.JTextArea();
        input_valor = new javax.swing.JFormattedTextField();
        C_tipos = new javax.swing.JComboBox();
        C_fornecedores = new javax.swing.JComboBox();
        C_categorias = new javax.swing.JComboBox();
        input_numero_documento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        input_data_pagamento = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_id_conta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Editar Conta a Pagar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 220, 40));

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setText("Titulo Conta: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 120, 20));

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setText("Valor total:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 120, 30));

        jLabel5.setBackground(java.awt.Color.white);
        jLabel5.setText("Data Vencimento:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 130, 30));

        btnRegistrar.setText("Editar");
        btnRegistrar.setBorder(new javax.swing.border.MatteBorder(null));
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, 140, 40));

        btnRegistrar1.setText("Cancelar");
        btnRegistrar1.setBorder(new javax.swing.border.MatteBorder(null));
        btnRegistrar1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 620, 140, 40));

        input_titulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                input_tituloKeyTyped(evt);
            }
        });
        getContentPane().add(input_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 178, -1));

        try {
            input_data_vencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        input_data_vencimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_data_vencimentoActionPerformed(evt);
            }
        });
        input_data_vencimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                input_data_vencimentoKeyTyped(evt);
            }
        });
        getContentPane().add(input_data_vencimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, 102, -1));

        C_parcela.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", " " }));
        C_parcela.setToolTipText("");
        getContentPane().add(C_parcela, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, -1, -1));

        jLabel4.setBackground(java.awt.Color.white);
        jLabel4.setText("Parcelas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 100, 30));

        jLabel6.setBackground(java.awt.Color.white);
        jLabel6.setText("DESCRIÇÃO:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        C_status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PENDENTE", "PAGO", "SEPARADO" }));
        C_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_statusActionPerformed(evt);
            }
        });
        getContentPane().add(C_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, -1, -1));

        jLabel7.setBackground(java.awt.Color.white);
        jLabel7.setText("Status");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, -1, -1));

        jScrollPane1.setBackground(java.awt.Color.white);

        txt_descricao.setColumns(20);
        txt_descricao.setRows(5);
        txt_descricao.setBorder(new javax.swing.border.MatteBorder(null));
        txt_descricao.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(txt_descricao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 230, -1));

        input_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_valorActionPerformed(evt);
            }
        });
        input_valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                input_valorKeyTyped(evt);
            }
        });
        getContentPane().add(input_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 102, -1));

        C_tipos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        C_tipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_tiposActionPerformed(evt);
            }
        });
        getContentPane().add(C_tipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 120, -1));

        C_fornecedores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        C_fornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_fornecedoresActionPerformed(evt);
            }
        });
        getContentPane().add(C_fornecedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 120, -1));

        C_categorias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        C_categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_categoriasActionPerformed(evt);
            }
        });
        getContentPane().add(C_categorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 120, -1));

        input_numero_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_numero_documentoActionPerformed(evt);
            }
        });
        input_numero_documento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                input_numero_documentoKeyTyped(evt);
            }
        });
        getContentPane().add(input_numero_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 178, -1));

        jLabel8.setBackground(java.awt.Color.white);
        jLabel8.setText("numero do documento");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 129, 22));

        jLabel9.setBackground(java.awt.Color.white);
        jLabel9.setText("Categoria");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, -1));

        jLabel10.setBackground(java.awt.Color.white);
        jLabel10.setText("Tipo Conta:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        jLabel11.setBackground(java.awt.Color.white);
        jLabel11.setText("Fornecedor");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, -1, 20));

        jLabel12.setBackground(java.awt.Color.white);
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("Correa Center");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 680, -1, 20));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_correcenterMenor.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, -1));

        jLabel14.setBackground(java.awt.Color.white);
        jLabel14.setText("Data Pagamento:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 130, 30));

        try {
            input_data_pagamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        input_data_pagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_data_pagamentoActionPerformed(evt);
            }
        });
        input_data_pagamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                input_data_pagamentoKeyTyped(evt);
            }
        });
        getContentPane().add(input_data_pagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 590, 102, -1));

        jLabel15.setText("id_conta:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 60, -1));
        getContentPane().add(txt_id_conta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Tipo_ContaDao tipo_conta = new Tipo_ContaDao();
        FornecedorDao fornecedor = new FornecedorDao();
        CategoriaDao categoria = new CategoriaDao();
        int parcelas = Integer.parseInt(this.C_parcela.getSelectedItem().toString());
        int id_tipo =  tipo_conta.retorna_id_tipo(this.C_tipos.getSelectedItem().toString());
        int id_categoria = categoria.retorna_id_categoria(this.C_categorias.getSelectedItem().toString());
        int id_fornecedor = fornecedor.retorna_id_fornecedor(this.C_fornecedores.getSelectedItem().toString());
        System.out.println(parcelas);
        System.out.println(this.C_status.getSelectedItem());
        System.out.println(this.C_parcela.getSelectedItem());
        System.out.println(this.input_titulo.getText());
        System.out.println(this.input_numero_documento.getText());
        System.out.println(this.input_data_vencimento.getText());
        System.out.println(this.txt_descricao.getText());
        System.out.println(this.input_valor.getText());

        System.out.println("Retorno campos validos: "+validaCampos());

        System.out.println(this.input_data_vencimento.getText().equals("  /  /    "));
        
        
        int id = Integer.parseInt(this.txt_id_conta.getText());
        //Verifica se os campos obrigatorios estão preenchidos, se sim (=1) inseri na tabela
        if (validaCampos() ==1){
                 ContaDao contaDao = new ContaDao();
                  String dt_pagamento ="";
           String dt_vencimento ="";
                
            try{
                
                
                //Inseri na Tabela Conta
                Conta conta = new Conta();

                String status = this.C_status.getSelectedItem().toString();
                conta.setTitulo_conta(this.input_titulo.getText());
                conta.setTipo_conta(id_tipo);
                conta.setDescricao(this.txt_descricao.getText());
                conta.setValor_titulo(Float.parseFloat(this.input_valor.getText()));
                conta.setData_validade(this.input_data_vencimento.getText());
                conta.setStatus(status);
                conta.setParcelas(parcelas);
                conta.setNumero_documento((this.input_numero_documento.getText()));
                conta.setId_fornecedor(id_fornecedor);
                conta.setTipo_categoria(id_categoria);
                conta.setData_pagamento(this.input_data_pagamento.getText());
                
                System.out.println("ID que está sendo deletado é: "+String.valueOf(id));
                contaDao.DeleteConta(id);
                contaDao.Inserir(conta);

                //Gera uma nova tela//

                this.dispose();
                TelaContasAPagar telainicial = new TelaContasAPagar();
                telainicial.setVisible(true);

            }catch(Exception ex){
                System.out.print(ex.getMessage());
            }

        }else{
            JOptionPane.showMessageDialog(null,"Verique se todos os campos estão preenchidos!");
        }

        // System.out.print(this.input_titulo.getText(),this.input_valor.getText(),this.input_data_vencimento.getText());

    }//GEN-LAST:event_btnRegistrarActionPerformed

      public int validaCampos(){
        int retornar = 0;
      if (this.input_titulo.getText().length()<=0){
          this.input_titulo.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.RED));
          retornar =0;
      }else if(this.input_valor.getText().length() <=0){
          this.input_valor.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.RED));
          retornar = 0;}
          
  
       
      else if(this.input_data_vencimento.getText().equals("  /  /    ")){
          retornar = 0;
          this.input_data_vencimento.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.RED));
      }
      else{
          retornar = 1;
      }
      return retornar;
    }
    private void btnRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar1ActionPerformed
        this.dispose();
        TelaContasAPagar inicio = new TelaContasAPagar();
        inicio.setVisible(true);
    }//GEN-LAST:event_btnRegistrar1ActionPerformed

    private void input_tituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_tituloKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_input_tituloKeyTyped

    private void input_data_vencimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_data_vencimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_data_vencimentoActionPerformed

    private void input_data_vencimentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_data_vencimentoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_input_data_vencimentoKeyTyped

    private void C_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C_statusActionPerformed

    private void input_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_valorActionPerformed

    private void input_valorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_valorKeyTyped
        String caracteres="0987654321.,";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_input_valorKeyTyped

    private void C_tiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_tiposActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_C_tiposActionPerformed

    private void C_fornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_fornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C_fornecedoresActionPerformed

    private void C_categoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_categoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C_categoriasActionPerformed

    private void input_numero_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_numero_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_numero_documentoActionPerformed

    private void input_numero_documentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_numero_documentoKeyTyped

    }//GEN-LAST:event_input_numero_documentoKeyTyped

    private void input_data_pagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_data_pagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_data_pagamentoActionPerformed

    private void input_data_pagamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_data_pagamentoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_input_data_pagamentoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox C_categorias;
    private javax.swing.JComboBox C_fornecedores;
    private javax.swing.JComboBox C_parcela;
    private javax.swing.JComboBox C_status;
    private javax.swing.JComboBox C_tipos;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrar1;
    private javax.swing.JFormattedTextField input_data_pagamento;
    private javax.swing.JFormattedTextField input_data_vencimento;
    private javax.swing.JTextField input_numero_documento;
    private javax.swing.JTextField input_titulo;
    private javax.swing.JFormattedTextField input_valor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_descricao;
    private javax.swing.JLabel txt_id_conta;
    // End of variables declaration//GEN-END:variables
}
