/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelaInicial;

import Classe.ListaConta;
import Dao.ContaDao;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author treinamento
 */
public class TelaContaUnica extends javax.swing.JFrame {
private int id=0;
    /**
     * Creates new form TelaContaUnica
     */
     public TelaContaUnica() {
        initComponents();
    }
    public TelaContaUnica(int id_frameprincipal){
        initComponents();
         this.setLocationRelativeTo(null);
       
        id= id_frameprincipal;
      
        
        ContaDao dao = new ContaDao();
   
    for (ListaConta conta :dao.RetornaConta(id)){
          this.var_numero_documento.setText(String.valueOf(conta.getNumero_documento()));
          this.var_tipoConta1.setText(conta.getTitulo_conta());
          this.var_fornecedor.setText(conta.getNome_fornecedor());
          this.var_categoria.setText(conta.getNome_categoria());
          this.var_descricao.setText(conta.getDescricao());
    }
    
        CarregaTabela1();
      
   

   
       
    }
    
      public void CarregaTabela1(){
         
            DefaultTableModel modelo = (DefaultTableModel) this.table_conta_unica.getModel(); //Definindo modelo da tabela;
            this.table_conta_unica.getColumnModel().getColumn(0).setMinWidth(0); // Oculta Coluna
            this.table_conta_unica.getColumnModel().getColumn(0).setMaxWidth(0); // Oculta Coluna

            modelo.setNumRows(0);
            DecimalFormat df = new DecimalFormat("#,###.00");
            DecimalFormat df2 = new DecimalFormat("######.00"); //Criando formatação Decimal
            //Definindo o tamanho da Coluna; Se quiser
            
        ContaDao dao = new ContaDao();
       
        
        try{
            
        
        for(ListaConta c : dao.RetornaConta(id)){
            
            //Pegando a data do banco no format yyyy-mm-dd e passando para dd/MM/yyyy para visualizar no relatorio
            SimpleDateFormat formato =  new SimpleDateFormat("dd/MM/yyyy");          
            java.util.Date d1 =  new SimpleDateFormat("yyyy-MM-dd").parse(c.getData_vencimento_inicio());
            Calendar cal = Calendar.getInstance();
           
            cal.setTime(d1);
           
            
            
          
            modelo.addRow(new Object[]{
                c.getId_conta(),
                c.getId_item(),
                c.getTitulo_conta(),
                c.getNome_tipo(),
                formato.format(cal.getTime()),         
                df2.format(c.getValor_conta()),
                c.getStatus()
            });

        }
        }catch(Exception ex){
            System.out.println("Carrega tabela: " + ex.getMessage());
        }
            
      }
      
      
      
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        table_conta_unica = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        var_descricao = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        B_pagamento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label_teste = new javax.swing.JLabel();
        var_numero_documento = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        var_fornecedor = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        var_tipoConta1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        var_categoria = new javax.swing.JLabel();
        B_pagamento1 = new javax.swing.JButton();
        B_pagamento2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 108, 30));

        table_conta_unica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id_conta", "código", "Titulo da Conta", "Tipo Conta", "Data Vencimento Inicio", "Valor", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_conta_unica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_conta_unicaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(table_conta_unica);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 640, 200));

        jScrollPane1.setOpaque(false);

        var_descricao.setEditable(false);
        var_descricao.setColumns(20);
        var_descricao.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        var_descricao.setRows(5);
        var_descricao.setBorder(new javax.swing.border.MatteBorder(null));
        var_descricao.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(var_descricao);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 220, 90));

        jButton2.setText("Alterar para Pendente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 170, 44));

        B_pagamento.setText("Alterar para Pago");
        B_pagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_pagamentoActionPerformed(evt);
            }
        });
        jPanel1.add(B_pagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 170, 44));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Descrição:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 20));

        label_teste.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_teste.setText("NUMERO DOCUMENTO:");
        jPanel1.add(label_teste, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 23));

        var_numero_documento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        var_numero_documento.setText("jLabel1");
        jPanel1.add(var_numero_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 50, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("FORNECEDOR:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 105, -1));

        var_fornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        var_fornecedor.setText("jLabel2");
        jPanel1.add(var_fornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 120, -1));

        jButton3.setText("Excluir Conta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 170, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("TITULO CONTA:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 130, -1));

        var_tipoConta1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        var_tipoConta1.setText("jLabel2");
        jPanel1.add(var_tipoConta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("CATEGORIA:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 105, -1));

        var_categoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        var_categoria.setText("jLabel2");
        jPanel1.add(var_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 60, -1));

        B_pagamento1.setText("Alterar para Separado");
        B_pagamento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_pagamento1ActionPerformed(evt);
            }
        });
        jPanel1.add(B_pagamento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 170, 44));

        B_pagamento2.setText("Editar Conta");
        B_pagamento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_pagamento2ActionPerformed(evt);
            }
        });
        jPanel1.add(B_pagamento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 170, 44));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 920, 430));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo_CorreCenter.jpeg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setMaximumSize(new java.awt.Dimension(1280, 263));
        jLabel3.setMinimumSize(new java.awt.Dimension(820, 263));
        jLabel3.setPreferredSize(new java.awt.Dimension(1220, 263));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, 0, 1150, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_conta_unicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_conta_unicaMouseClicked
     
    }//GEN-LAST:event_table_conta_unicaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TelaContasAPagar principal = new TelaContasAPagar();
        principal.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void B_pagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_pagamentoActionPerformed
        int indice = this.table_conta_unica.getSelectedRow();
        
        if(indice != -1){
            int id_conta = (int) this.table_conta_unica.getValueAt(indice, 0);
            System.out.println("TESTE : " + indice+" "+ id_conta);
             ContaDao dao = new ContaDao();
             dao.UpdatePago(id_conta);
             CarregaTabela1();
        }
        else{
            JOptionPane.showMessageDialog(null,"Selecione item que deseja alterar");
        }
        
    }//GEN-LAST:event_B_pagamentoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           int indice = this.table_conta_unica.getSelectedRow(); 
         if(indice != -1){
            int id_conta = (int) this.table_conta_unica.getValueAt(indice, 0);
            System.out.println("TESTE : " + indice+" "+ id_conta);
             ContaDao dao = new ContaDao();
             dao.UpdatePendente(id_conta);
             CarregaTabela1();
        }
        else{
            JOptionPane.showMessageDialog(null,"Selecione item que deseja alterar");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ContaDao dao = new ContaDao();
        dao.DeleteConta(id);
        TelaContasAPagar_Pesquisa pesquisa = new TelaContasAPagar_Pesquisa();
        pesquisa.setVisible(true);
        JOptionPane.showMessageDialog(null, "Conta Excluida");
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void B_pagamento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_pagamento1ActionPerformed
                 int indice = this.table_conta_unica.getSelectedRow(); 
         if(indice != -1){
            int id_conta = (int) this.table_conta_unica.getValueAt(indice, 0);
            System.out.println("TESTE : " + indice+" "+ id_conta);
             ContaDao dao = new ContaDao();
             dao.UpdateSeparado(id_conta);
             CarregaTabela1();
        }
        else{
            JOptionPane.showMessageDialog(null,"Selecione item que deseja alterar");
        }
    }//GEN-LAST:event_B_pagamento1ActionPerformed

    private void B_pagamento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_pagamento2ActionPerformed
       EditarConta editaconta = new EditarConta(id);
            editaconta.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_B_pagamento2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaContaUnica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaContaUnica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaContaUnica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaContaUnica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaContaUnica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_pagamento;
    private javax.swing.JButton B_pagamento1;
    private javax.swing.JButton B_pagamento2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel label_teste;
    private javax.swing.JTable table_conta_unica;
    private javax.swing.JLabel var_categoria;
    private javax.swing.JTextArea var_descricao;
    private javax.swing.JLabel var_fornecedor;
    private javax.swing.JLabel var_numero_documento;
    private javax.swing.JLabel var_tipoConta1;
    // End of variables declaration//GEN-END:variables
}
