/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelaInicial;

import Classe.Categoria;
import Classe.Fornecedor;
import Dao.CategoriaDao;
import Dao.FornecedorDao;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author fmoliveira
 */
public class TelaCategoria extends javax.swing.JFrame {

    /**
     * Creates new form TelaCategoria
     */
    public TelaCategoria() {
        initComponents();
         this.setLocationRelativeTo(null);
           this.getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        j_id_categoria = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        j_nome_categoria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setText("Editar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 128, 40));

        jButton7.setText("Consultar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 128, 40));

        jLabel1.setText("id_categoria");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        j_id_categoria.setEditable(false);
        j_id_categoria.setEnabled(false);
        j_id_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_id_categoriaActionPerformed(evt);
            }
        });
        getContentPane().add(j_id_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 78, -1));

        jButton5.setText("Excluir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 128, 40));
        getContentPane().add(j_nome_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 90, -1));

        jLabel2.setText("Nome_categoria");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        jButton4.setText("Voltar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 128, 40));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Registrar Categoria");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 264, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_correcenterMenor.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j_id_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_id_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_id_categoriaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        CategoriaDao funcao_categoria= new CategoriaDao();
        Categoria categoria = new Categoria();
        categoria.setId_categoria(Integer.parseInt(this.j_id_categoria.getText()));
        categoria.setNome_categoria(this.j_nome_categoria.getText());
        funcao_categoria.DeleteCategoria(this.j_nome_categoria.getText());
        
        this.j_nome_categoria.setText("");
         this.j_id_categoria.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here: this.dispose();
        this.dispose();
        TelaContasAPagar telainicial = new TelaContasAPagar();
        telainicial.setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       CategoriaDao funcao_categoria= new CategoriaDao();
        Categoria categoria = new Categoria();
        //categoria.setId_categoria(Integer.parseInt(this.j_id_categoria.getText()));
        
        
        
        if (this.j_nome_categoria.getText().length()>0){
             categoria.setNome_categoria(this.j_nome_categoria.getText());
              funcao_categoria.InserirCategoria(categoria);
             
        this.j_nome_categoria.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "verifique se todos os campos estão preenchidos");
        }
      
        
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       int id_categoria=0;
         CategoriaDao funcao_categoria= new CategoriaDao();
        id_categoria=funcao_categoria.retorna_nome_categoria(this.j_nome_categoria.getText());
            
     
        
        
          if (id_categoria>0){
            this.j_id_categoria.setText(String.valueOf(id_categoria));
        }
        
        else{
            JOptionPane.showMessageDialog(null, "Nenhuma Categoria encontrada com esse nome");
            this.j_id_categoria.setText("");
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         CategoriaDao funcao_categoria= new CategoriaDao();
        Categoria categoria = new Categoria();
        categoria.setId_categoria(Integer.parseInt(this.j_id_categoria.getText()));
        categoria.setNome_categoria(this.j_nome_categoria.getText());

     

        funcao_categoria.UpdateCategoria(categoria);
        
        
        this.dispose();
            TelaCategoria telacategoria = new TelaCategoria();
            telacategoria.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField j_id_categoria;
    private javax.swing.JTextField j_nome_categoria;
    // End of variables declaration//GEN-END:variables
}
